# Generated by Django 5.2.4 on 2025-07-31 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_commentvote'),
        ('users', '0002_alter_userprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_build_comment',
            field=models.BooleanField(default=True, help_text='Receive notifications when someone comments on your build'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_build_like',
            field=models.BooleanField(default=True, help_text='Receive notifications when someone likes your build'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_comment_reply',
            field=models.BooleanField(default=True, help_text='Receive notifications when someone replies to your comment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_comment_vote',
            field=models.BooleanField(default=False, help_text='Receive notifications when someone votes on your comment'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('build_like', 'Build Like'), ('build_comment', 'Build Comment'), ('comment_reply', 'Comment Reply'), ('comment_vote', 'Comment Vote')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builds.build')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builds.comment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='users_notif_recipie_458498_idx'), models.Index(fields=['recipient', 'is_read'], name='users_notif_recipie_2469dd_idx')],
            },
        ),
    ]
