# Generated by Django 5.2.4 on 2025-07-31 19:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_notify_on_build_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile picture', max_length=255, null=True, verbose_name='image'),
        ),
    ]
