# Generated by Django 5.2.4 on 2025-07-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='category',
            field=models.CharField(choices=[('PVE', 'PvE'), ('PVP', 'PvP'), ('BOTH', 'Both')], default='PVE', max_length=10),
        ),
    ]
