# Generated by Django 5.2.4 on 2025-07-30 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_build_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='likes',
        ),
        migrations.AddField(
            model_name='build',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_builds', to=settings.AUTH_USER_MODEL),
        ),
    ]
