# Generated by Django 5.2.4 on 2025-07-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_remove_build_likes_build_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='likes',
            new_name='liked_by',
        ),
    ]
