# Generated by Django 5.2.4 on 2025-07-31 19:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_commentvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
