# Generated by Django 5.2.4 on 2025-08-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0008_remove_build_image_buildimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='arcane',
            field=models.PositiveIntegerField(blank=True, help_text='Arcane stat', null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='dexterity',
            field=models.PositiveIntegerField(blank=True, help_text='Dexterity stat', null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='endurance',
            field=models.PositiveIntegerField(blank=True, help_text='Endurance stat', null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='faith',
            field=models.PositiveIntegerField(blank=True, help_text='Faith stat', null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='intelligence',
            field=models.PositiveIntegerField(blank=True, help_text='Intelligence stat', null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Character level', null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='mind',
            field=models.PositiveIntegerField(blank=True, help_text='Mind stat', null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='strength',
            field=models.PositiveIntegerField(blank=True, help_text='Strength stat', null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='vigor',
            field=models.PositiveIntegerField(blank=True, help_text='Vigor stat', null=True),
        ),
    ]
