# Generated by Django 5.2.4 on 2025-08-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0009_build_arcane_build_dexterity_build_endurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
